name: Daily Standup
description: Daily collaborative writing check-in for serialized and independent stories
title: "Daily Standup"
labels: ["standup", "writing"]

body:
  - type: input
    id: meeting_date
    attributes:
      label: "Meeting Date"
      description: "Enter today's date"
      placeholder: "2026-02-06"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Collaborative Writing Daily Standup
        
        **Duration**: 30-60 minutes
        **Participants**: Jeff / Sarah

  - type: textarea
    id: serial_status_jeff
    attributes:
      label: "Serial Status - Jeff (Draft)"
      description: "Today's Chapter, Draft Status, Reason if not done, Anything for Sarah's attention"
      placeholder: |
        Today's Chapter: Chapter __-__
        Draft Status: Not started / In Progress / Done
        If not done, reason: ____
        Anything for Sarah's attention: ____

  - type: textarea
    id: serial_status_sarah
    attributes:
      label: "Serial Status - Sarah (Edits/Publishing)"
      description: "Chapter today, Editing status, Need draft from Jeff, Publish status"
      placeholder: |
        Chapter today: Chapter __-__
        Editing: Not started / In Progress / Done
        Need draft from Jeff: No / Yes
        Publish: Not published / Published (Platform: ____)

  - type: textarea
    id: serial_next
    attributes:
      label: "Next Serial Goals"
      description: "Draft target and Editing/Publishing target for tomorrow"
      placeholder: |
        Jeff: Draft target for tomorrow
        Sarah: Editing or Publishing Target

  - type: textarea
    id: independent_status
    attributes:
      label: "Independent Stories (Optional)"
      description: "Progress on independent articles this week"
      placeholder: |
        Any progress this week: Yes/No
        Current phase: Idea / Draft / Edit / Publish
        Progress this meeting: Yes/No
        Next responsible: Jeff / Sarah

  - type: textarea
    id: brainstorming
    attributes:
      label: "Brainstorming"
      description: "Key points for tomorrow or new independent story ideas"
      placeholder: |
        Key points for tomorrow's chapter
        Or new independent story ideas (Setup/Conflict/Scene)

  - type: textarea
    id: roadblock
    attributes:
      label: "Roadblocks"
      description: "Any blockers affecting progress"
      placeholder: |
        Any blockers: None/Yes
        Blocker: ____
        Owner: Jeff / Sarah
        Affecting serial?: Yes/No

  - type: textarea
    id: closing
    attributes:
      label: "Closing Confirmation"
      description: "Meeting wrap-up checklist"
      placeholder: |
        All info updated?: Yes/No
        Minimum deliverable set?: Yes/No
        Next meeting focus: ____

